version: "3.1"
services:
  api:
    image: node-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: "."
    volumes:
      - app:/usr/src/app
    env_file:
      - .env
    ports:
      - "80:5000"
volumes:
  app:

